---
# tasks file for podman_systemd_container

- name: Check if user exists
  user:
    name: "{{ container_run_as_user }}"

- name: Check if user exists in subuid file
  lineinfile:
    path: /etc/subuid
    regexp: "^{{ container_run_as_user }}:.*"
  check_mode: yes
  register: uid_exists
  ignore_errors: true

- name: Check if group exists in subgid file
  lineinfile:
    path: /etc/subgid
    regexp: "^{{ container_run_as_group }}:.*"
  check_mode: yes
  register: gid_exists
  ignore_errors: true

- name: Ensure user exists in subuid file, if it was missing
  lineinfile:
    path: /etc/subuid
    regexp: "^{{ container_run_as_user }}:.*"
    line: "{{ container_run_as_user }}:305536:65536"
    create: yes
    mode: '0644'
    owner: root
    group: root
  when: uid_exists.changed and container_run_as_user != 'root'

- name: Ensure group is in subgid file, if it was missing
  lineinfile:
    path: /etc/subgid
    regexp: "^{{ container_run_as_group }}:.*"
    line: "{{ container_run_as_group }}:305536:65536"
    create: yes
    mode: '0644'
    owner: root
    group: root
  when: gid_exists.changed and container_run_as_user != 'root'

- name: Increase user namespaces
  lineinfile:
    path: /etc/sysctl.d/userns.conf
    regexp: "^user.max_user_namespaces=.*"
    line: "user.max_user_namespaces=28633"
  check_mode: yes
  ignore_errors: true
  