---
# tasks file for podman_systemd_container

- name: Install service file for {{ container_name }} container
  template:
    dest: /etc/systemd/system/{{ container_name }}.service
    src: templates/podman_container.service.j2
  register: container_service

- name: make sure that {{ container_name }} is enabled and started
  systemd:
    daemon_reload: yes
    name: '{{ container_name }}.service'
    state: restarted
    enabled: yes
  when: container_service.changed
