---
# tasks file for podman_systemd_container

- name: Ensure container-tools and slirp4netns are installed
  package:
    name: "{{ item }}"
    state: installed
  with_list:
    - podman
    - buildah
    - skopeo
    - runc
    - slirp4netns

- name: Ensure podman-docker is installed
  package:
    name: podman-docker
    state: installed
